In [1]:
import TimeTagger

In [2]:
time_tagger = TimeTagger.createTimeTagger()

In [3]:
syncMeas = TimeTagger.SynchronizedMeasurements(time_tagger)
taggerSync = syncMeas.getTagger()
counter = TimeTagger.Counter(taggerSync, [1, 2])
countrate = TimeTagger.Countrate(taggerSync, [3, 4])
counter2 = TimeTagger.Counter(time_tagger, [3, 4])

In [5]:
counter2.isRunning(), countrate.isRunning(), syncMeas.isRunning()

(True, False, False)

In [13]:
duration = 1E12
syncMeas.startFor(duration)
counter.getData(), countrate.getData()

(array([[0],
        [0]]),
 array([nan, nan]))

In [14]:
counter2.getData()

array([[0],
       [0]])

In [6]:
fw = TimeTagger.FileWriter(time_tagger,'test',[1])

In [8]:
fw.stop()
fw.isRunning()

False

In [10]:
import numpy as np

In [13]:
n_pixel = 256
pixel_time = 1/200E3
integ_time = 3E9
pixel_pattern_start = np.linspace(0, n_pixel, num=n_pixel, endpoint=False, dtype=int) * (pixel_time * 1e12)
pixel_pattern_end = pixel_pattern_start +  integ_time

pixel_start_chan = TimeTagger.EventGenerator(time_tagger, 2, pixel_pattern_start)
pixel_end_chan= TimeTagger.EventGenerator(time_tagger, 2, pixel_pattern_end)

In [15]:
pixel_start_chan.isRunning()

True

In [16]:
pixel_start_chan = TimeTagger.EventGenerator(taggerSync, 2, pixel_pattern_start)
pixel_end_chan= TimeTagger.EventGenerator(taggerSync, 2, pixel_pattern_end)

In [19]:
pixel_end_chan.getChannel()

1004

In [17]:
pixel_start_chan.isRunning()

False

# file writer

In [ ]:
filename = ""
chanels = []
duration = 0 # in ps

In [ ]:
file_writer = TT.FileWriter(time_tagger, filename, channels)

In [ ]:
file_writer.startFor(duration)

# flim measurement

In [3]:
#if used file writer
time_tagger.reset()

In [4]:
laser = 1
frame = 3 
line = 2
photon = -4

n_bins = 256
binwidth = 49 # 12.5ns/256
n_pixel = 256

pixel_rate = 200e3
pixel_time = 1 / pixel_rate
integr_time = 3e9 # Integration time of 3 ms in picoseconds

In [5]:
import numpy as np

In [6]:
# EventGenerator(tagger, trigger_channel, pattern, trigger_divider, stop_channel)
#virtual channel
pixel_pattern_start = np.linspace(0, n_pixel, num=n_pixel, endpoint=False, dtype=int) * (pixel_time * 1e12)
pixel_pattern_end = pixel_pattern_start + integr_time

pixel_start_chan = TT.EventGenerator(time_tagger, line, pixel_pattern_start)
pixel_end_chan= TT.EventGenerator(time_tagger, line, pixel_pattern_end)

In [7]:
#ConstantFractionDiscriminator(tagger, channels, search_window)
#virtual channel
photon_cfd_chan = TT.ConstantFractionDiscriminator(time_tagger, (photon,), 10*1000)

In [8]:
#DelayedChannel(tagger, input_channel, delay)
#virtual channel
delayed_laser_chan = TT.DelayedChannel(time_tagger, laser, 11.5e3)

In [ ]:
sync = TT.SynchronizedMeasurements(time_tagger)
sync_tagger = sync.getTagger()

In [9]:
#possibly don't need frame
flim = TT.Flim(time_tagger, 
               start_channel = delayed_laser_chan.getChannel(), 
               click_channel = photon_cfd_chan.getChannels()[0], 
               pixel_begin_channel=pixel_start_chan.getChannel(), 
               n_pixels    = n_pixel*n_pixel, 
               n_bins      = n_bins, 
               binwidth    = binwidth, 
               pixel_end_channel= pixel_end_chan.getChannel(), 
               frame_begin_channel= frame)

In [ ]:
duration = 1E12
flim.startFor(duration)

In [ ]:
flim_3d = flim.getSummedFrames().reshape(256,256,256)

In [ ]:
flim_mean = flim_3d.sum(2)

In [ ]:
from matplotlib.pyplot import *

In [ ]:
figure(figsize=[7,7])
imshow(flim_mean)
colorbar()

In [ ]:
#flim#.getData()

In [ ]:
x=flim.getSummedFramesEx()

In [ ]:
x.getHistograms()

In [ ]:
flim.getSummedFrames().shape